### ISSUE TITLE
Add support for flatpak-external-data-checker

### ISSUE THREAD

**Issue by dbnicholson** [flathub/org.endlessos.Key#6]
We need to add the `x-checker-data` metadata to the various modules so that flatpak-external-data-checker can tell us about updates. See https://github.com/endlessm/endless-key-flatpak/issues/45 for the equivalent work on the devel flatpak.

**Comment by starnight** [comment]
According to [flatpak-external-data-checker](https://github.com/flathub/flatpak-external-data-checker#on-flathub)'s document, Flathub runs flatpak-external-data-checker hourly for all Flatpak repos under [github.com/flathub](https://github.com/flathub).  So, we have to add `x-checker-data` into modules.
